---
# create Namespace

apiVersion: v1
kind: Namespace
metadata:
  name: cloudns
  labels:
    name: cloudns
---
# Create ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: cloudns
data:
  author: {{.Values.vars.author}}
  fastapi_service_hostname: http://fastapi-app
# ------
# Usage:
# ------
# kubectl apply -f cm.yml
# kubectl delete configmap config-map
